check/Makefile.am: add per-test valgrind targets
Original commit message from CVS:

* check/Makefile.am:
add per-test valgrind targets
* check/gst-libs/gdp.c: (GST_START_TEST),
(gst_data_protocol_suite), (main):
clean up

diff --git a/tests/check/Makefile.am b/tests/check/Makefile.am
--- a/tests/check/Makefile.am
+++ b/tests/check/Makefile.am
@@ -1,7 +1,9 @@
+CHECK_REGISTRY=$(top_builddir)/check/test-registry.xml
+
 TESTS_ENVIRONMENT=\
 	GST_PLUGIN_PATH_ONLY=yes \
 	GST_PLUGIN_PATH=$(top_builddir)/gst \
-	GST_REGISTRY=$(top_builddir)/check/test-registry.xml
+	GST_REGISTRY=$(CHECK_REGISTRY)
 
 plugindir = $(libdir)/gstreamer-@GST_MAJORMINOR@
 
@@ -21,6 +23,10 @@ clean-local:
 	for i in `find . -name ".libs" -type d`; do \
 	  rm -rf $$i; \
 	done
+
+$(CHECK_REGISTRY):
+	$(TESTS_ENVIRONMENT)					\
+	$(top_builddir)/tools/gst-register
 
 # FIXME: it'd be nicer to run the versioned register, but in that case
 # "make dist" complains about not finding gst-register-0.9.c
@@ -73,8 +79,7 @@ TESTS_TO_FIX =					\
 	gst/gstsystemclock			\
 	gst/gsttag				\
 	pipelines/cleanup			\
-	pipelines/simple_launch_lines		\
-	gst-libs/gdp
+	pipelines/simple_launch_lines
 
 # these need fixing because the threads cause segfaults under valgrind
 TESTS_THREADED =				\
@@ -95,16 +100,21 @@ check-local-disabled:
 	@true
 endif
 
-valgrind:
+# valgrind any given test by running make test.valgrind
+%.valgrind: % $(CHECK_REGISTRY)
+	@$(TESTS_ENVIRONMENT)					\
+	libtool --mode=execute					\
+	$(VALGRIND_PATH) -q --suppressions=$(srcdir)/gst.supp	\
+	--tool=memcheck --trace-children=yes			\
+	$*
+
+# valgrind all tests
+valgrind: $(TESTS)
 	@echo "Valgrinding tests ..."
 	$(TESTS_ENVIRONMENT) $(top_builddir)/tools/gst-register
 	@failed=0;							\
 	for t in $(filter-out $(VALGRIND_TESTS_DISABLE),$(TESTS)); do	\
-		$(TESTS_ENVIRONMENT)					\
-		CK_FORK=no						\
-		libtool --mode=execute					\
-		$(VALGRIND_PATH) -q --suppressions=$(srcdir)/gst.supp	\
-		--tool=memcheck $$t;					\
+		make $$t.valgrind;					\
 		if test "$$?" -ne 0; then                               \
                         echo "Valgrind error for test $$t";		\
 			failed=`expr $$failed + 1`;			\
@@ -114,4 +124,25 @@ valgrind:
 		echo "$$failed tests had leaks under valgrind";		\
 		false;							\
 	fi
+
+valgrindy: $(TESTS)
+	@echo "Valgrinding tests ..."
+	$(TESTS_ENVIRONMENT) $(top_builddir)/tools/gst-register
+	@failed=0;							\
+	for t in $(filter-out $(VALGRIND_TESTS_DISABLE),$(TESTS)); do	\
+		$(TESTS_ENVIRONMENT)					\
+		libtool --mode=execute					\
+		$(VALGRIND_PATH) -q --suppressions=$(srcdir)/gst.supp	\
+		--tool=memcheck --trace-children=yes			\
+		$$t;							\
+		if test "$$?" -ne 0; then                               \
+                        echo "Valgrind error for test $$t";		\
+			failed=`expr $$failed + 1`;			\
+                fi;							\
+	done;								\
+	if test "$$failed" -ne 0; then					\
+		echo "$$failed tests had leaks under valgrind";		\
+		false;							\
+	fi
+
 
